### ISSUE TITLE
[Windows 7 x64] json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Shazgul** [yezz123/SoIG#1]
Getting following Error while using SoIG on Windows, any Fix?

[+] getting profile ...Traceback (most recent call last):
  File "main.py", line 16, in <module>
    ig = main(user=args["username"])
  File "C:\OSINT\SoIG-master/.lib\api.py", line 62, in __init__
    self.get_profile()
  File "C:\OSINT\SoIG-master/.lib\api.py", line 69, in get_profile
    self.data = json.loads(more_data[3].get_text()[21:].strip(';'))
  File "C:\Python3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Python3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by yezz123** [comment]
use termux or linux
