### ISSUE TITLE
Doesn't work...get this error msg

### ISSUE THREAD

**Issue by benbangli78** [yezz123/SoIG#2]
+] getting profile ...Traceback (most recent call last):
  File "/home/benbangli/SoIG/main.py", line 16, in <module>
    ig = main(user=args["username"])
  File "/home/benbangli/SoIG/.lib/api.py", line 62, in __init__
    self.get_profile()
  File "/home/benbangli/SoIG/.lib/api.py", line 69, in get_profile
    self.data = json.loads(more_data[3].get_text()[21:].strip(';'))
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by yezz123** [comment]
Give me please More information!

**Comment by yezz123** [comment]
you can check this issue #4
