### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bursog** [yezz123/SoIG#5]
getting profile ...Traceback (most recent call last):
  File "C:\Users\NADIRPC\Downloads\My-Github\SoIG\main.py", line 19, in <module>
    ig = main(user=args["username"])
  File "C:\Users\NADIRPC\Downloads\My-Github\SoIG\api\api.py", line 61, in __init__
    self.get_profile()
  File "C:\Users\NADIRPC\Downloads\My-Github\SoIG\api\api.py", line 69, in get_profile
    self.data = json.loads(more_data[3].get_text()[21:].strip(';'))
  File "C:\Users\NADIRPC\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\NADIRPC\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\NADIRPC\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by yezz123** [comment]
This issue doesn’t relate to the API itself 😅!
I just Check the API Work Clean and smooth
