### ISSUE TITLE
Program throws errors

### ISSUE THREAD

**Issue by lingywingy** [yezz123/SoIG#8]
Command ran: `python3 main.py -u (username)`

Python on version 3.10.5, running on Kali Linux

```
[+] getting profile ...Traceback (most recent call last):
  File "/home/kali/SoIG/main.py", line 19, in <module>
    ig = main(user=args["username"])
  File "/home/kali/SoIG/api/api.py", line 64, in __init__
    self.get_profile()
  File "/home/kali/SoIG/api/api.py", line 76, in get_profile
    self.data = json.loads(more_data[3].get_text()[21:].strip(";"))
IndexError: list index out of range
```

**Comment by finalsecure** [comment]
Same issue... @yezz123 ??

**Comment by Oraclis** [comment]
same here

**Comment by RiteshSec** [comment]
Hi has anyone found a solution for this issue?

The HTML content of an Instagram user page I see that there is no element with attribute ```type``` having value as ```text/javascript```. 

Hence there will be no items in ```more_data``` array in ```api.py``` file and hence the error. This might be because Instagram has updated its website format.

@yezz123 can you check the new format and update the code accordingly?
